### ISSUE TITLE
Issue building on Oracle EL 7 with UEK

### ISSUE THREAD

**Issue by mattboston** [snuf/iomemory-vsl4#40] opened 2022-04-12 15:08 UTC
### Bug description
If we try either a "make rpm" or "make dkms" we're getting errors. I would prefer DKMS, but would settle for either. I've also tried the latest official driver and their steps to build DKMS, but it fails as well. 

### How to reproduce
```
git clone https://github.com/snuf/iomemory-vsl4.git
cd iomemory-vsl4
git checkout <tag or some-branch>
make rpm
or 
make dkms
```

### Environment information
Information about the system the module is used on
1. Linux kernel compiled against (uname -a): Linux dcokvmh01.frtservices.com 5.4.17-2136.305.5.4.el7uek.x86_64 <span>#</span>2 SMP Mon Mar 28 19:02:05 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
2. The C compiler version used (gcc --version): gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)
3. distribution, and version (cat /etc/os-release)
```
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
```
4. Tag or Branch of iomemory-vsl4 that is being compiled: main (commit 265a128c4d4838c4d1a52591053c2de7df69a733)
5. FIO device used: SanDisk FusionIO SX350
6. Installed Kernel/UEK/DKMS packages:
```
[root@dcokvmh01 ~]# rpm -qa | egrep -i 'kernel|uek' | sort
abrt-addon-kerneloops-2.1.11-60.0.1.el7.x86_64
kernel-3.10.0-1160.59.1.el7.x86_64
kernel-3.10.0-1160.62.1.el7.x86_64
[dkms.log](https://github.com/RemixVSL/iomemory-vsl4/files/8474141/dkms.log)
[rpm.log](https://github.com/RemixVSL/iomemory-vsl4/files/8474142/rpm.log)

kernel-debug-devel-3.10.0-1160.62.1.el7.x86_64
kernel-devel-3.10.0-1160.59.1.el7.x86_64
kernel-devel-3.10.0-1160.62.1.el7.x86_64
kernel-headers-3.10.0-1160.62.1.el7.x86_64
kernel-tools-3.10.0-1160.62.1.el7.x86_64
kernel-tools-libs-3.10.0-1160.62.1.el7.x86_64
kernel-uek-5.4.17-2136.305.5.4.el7uek.x86_64
kernel-uek-devel-5.4.17-2136.305.5.4.el7uek.x86_64
kernel-uek-tools-5.4.17-2136.305.5.4.el7uek.x86_64

[root@dcokvmh01 ~]# rpm -qa dkms
dkms-3.0.3-1.el7.noarch
```
Fixed formatting

**Comment by mattboston** [comment] 2022-04-12 15:08
[dkms.log](https://github.com/RemixVSL/iomemory-vsl4/files/8474158/dkms.log)
[rpm.log](https://github.com/RemixVSL/iomemory-vsl4/files/8474159/rpm.log)

**Comment by mattboston** [comment] 2022-04-12 16:54
Also tried the following:

```
git checkout v5.12.1
make dkms
```

And the output:
```
[root@dcokvmh01 iomemory-vsl4]# make dkms
cd root/usr/src/iomemory-vsl4-4.3.7 && \
        make clean
make[1]: Entering directory `/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7'
make \
        -j32 \
        -C /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/build \
        FIO_DRIVER_NAME=iomemory-vsl4 \
        FUSION_DRIVER_DIR=/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7 \
        M=/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7 \
        EXTRA_CFLAGS+="-I/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/include -DBUILDING_MODULE -DLINUX_IO_SCHED -Wall" \
        KFIO_LIB=kfio/x86_64_cc48_libkfio.o_shipped \
        clean
make[2]: Entering directory `/usr/src/kernels/5.4.17-2136.305.5.4.el7uek.x86_64'
make[2]: Leaving directory `/usr/src/kernels/5.4.17-2136.305.5.4.el7uek.x86_64'
rm -rf include/fio/port/linux/kfio_config.h kfio_config license.c
make[1]: Leaving directory `/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7'
cd root/usr/src/iomemory-vsl4-4.3.7 && \
        make dkms
make[1]: Entering directory `/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7'
./module_operations.sh -n "iomemory-vsl4" -v "e2084ae" -d
Adding module version 5.4.17-e2084ae-4.3.7 to source license.c
grep: license.c: No such file or directory
/usr/src/iomemory-vsl4-5.4.17-e2084ae already exists.
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Ok:  already patched with 5.4.17-e2084ae-4.3.7
Adding, buidling and installing iomemory-vsl4/5.4.17-e2084ae with DKMS
Deprecated feature: REMAKE_INITRD

Building module:
cleaning build area...
'make' DKMS_KERNEL_VERSION=5.4.17-2136.305.5.4.el7uek.x86_64.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.17-2136.305.5.4.el7uek.x86_64 (x86_64)
Consult /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/make.log for more information.
make[1]: *** [dkms] Error 10
make[1]: Leaving directory `/root/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7'
make: *** [dkms] Error 2
```

```
[root@dcokvmh01 iomemory-vsl4]# cat /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/make.log
DKMS make.log for iomemory-vsl4-5.4.17-e2084ae for kernel 5.4.17-2136.305.5.4.el7uek.x86_64 (x86_64)
Tue Apr 12 12:52:49 EDT 2022
make[2]: Entering directory `/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build'
sed -i 's/Proprietary/GPL/g' Kbuild

Change found in target kernel: KERNELVER KERNEL_SRC 
Running clean before building driver

make[3]: Entering directory `/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build'
make \
        -j32 \
        -C /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/build \
        FIO_DRIVER_NAME=iomemory-vsl4 \
        FUSION_DRIVER_DIR=/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build \
        M=/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build \
        EXTRA_CFLAGS+="-I/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/include -DBUILDING_MODULE -DLINUX_IO_SCHED -Wall" \
        KFIO_LIB=kfio/x86_64_cc48_libkfio.o_shipped \
        clean
make[4]: Entering directory `/usr/src/kernels/5.4.17-2136.305.5.4.el7uek.x86_64'
make[4]: Leaving directory `/usr/src/kernels/5.4.17-2136.305.5.4.el7uek.x86_64'
rm -rf include/fio/port/linux/kfio_config.h kfio_config license.c
make[3]: Leaving directory `/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build'
if [ "48" -gt "75" ];then \
        if [ ! -f "kfio/x86_64_cc48_libkfio.o_shipped" ];then \
                cp kfio/x86_64_cc75_libkfio.o_shipped kfio/x86_64_cc48_libkfio.o_shipped; \
        fi \
fi
./kfio_config.sh -a x86_64 -o include/fio/port/linux/kfio_config.h -k /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/build -p -d /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfio_config -l 0 -s /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/source
Detecting Kernel Flags
Config dir         : /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfio_config
Output file        : include/fio/port/linux/kfio_config.h
Kernel output dir  : /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/build
Kernel source dir  : /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/source
Starting tests:
  1649782371.546  KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS...
  1649782371.645  KFIOC_X_TASK_HAS_CPUS_MASK...
  1649782371.734  KFIOC_X_LINUX_HAS_PART_STAT_H...
  1649782371.821  KFIOC_X_BLK_ALLOC_QUEUE_NODE_EXISTS...
  1649782371.921  KFIOC_X_HAS_MAKE_REQUEST_FN...
  1649782372.011  KFIOC_X_GENHD_PART0_IS_A_POINTER...
  1649782372.117  KFIOC_X_BIO_HAS_BI_BDEV...
Started tests, waiting for completions...
  1649782375.274  KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS=1
  1649782375.323  KFIOC_X_TASK_HAS_CPUS_MASK=1
  1649782375.373  KFIOC_X_LINUX_HAS_PART_STAT_H=0
  1649782375.423  KFIOC_X_BLK_ALLOC_QUEUE_NODE_EXISTS=1
  1649782375.472  KFIOC_X_HAS_MAKE_REQUEST_FN=1
  1649782375.521  KFIOC_X_GENHD_PART0_IS_A_POINTER=0
  1649782375.571  KFIOC_X_BIO_HAS_BI_BDEV=0
Finished
1649782375.594  Exiting
Preserving configdir due to '-p' option: /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfio_config
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make \
    -j32 \
-C /lib/modules/5.4.17-2136.305.5.4.el7uek.x86_64/build \
FIO_DRIVER_NAME=iomemory-vsl4 \
FUSION_DRIVER_DIR=/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build \
M=/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build \
EXTRA_CFLAGS+="-I/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/include -DBUILDING_MODULE -DLINUX_IO_SCHED -Wall" \
INSTALL_MOD_DIR=extra/fio \
INSTALL_MOD_PATH= \
KFIO_LIB=kfio/x86_64_cc48_libkfio.o_shipped \
modules
make[3]: Entering directory `/usr/src/kernels/5.4.17-2136.305.5.4.el7uek.x86_64'
printf '#include "linux/module.h"\nMODULE_LICENSE("GPL");\n' >/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/license.c
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/main.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/dbgset.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/pci.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/sysrq.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/driver_init.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfio.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/errno.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/state.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kmsg.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/six_lock.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcache.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kmem.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kscatter.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/ktime.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/sched.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/cdev.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kscsi.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kscsi_host.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kblock.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcpu.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcondvar.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/common_kinfo.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kinfo.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kinit.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfio_common.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/khotplug.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcsr.o
  SHIPPED /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfio/x86_64_cc48_libkfio.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/module_param.o
  CC [M]  /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/license.o
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c: In function ‘kfio_create_proc_fops_entry’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:227:55: warning: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [enabled by default]
     return proc_create_data(name, mode, base, (struct proc_ops *)fops, data);
                                                       ^
In file included from /var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:37:0:
./include/linux/proc_fs.h:45:31: note: expected ‘const struct file_operations *’ but argument is of type ‘struct proc_ops *’
 extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
                               ^
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c: In function ‘kfio_set_file_ops_llseek_handler’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:300:30: error: dereferencing pointer to incomplete type
     ((struct proc_ops *)pops)->proc_lseek = (file_ops_llseek_fn)llseek;
                              ^
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c: In function ‘kfio_set_file_ops_read_handler’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:305:30: error: dereferencing pointer to incomplete type
     ((struct proc_ops *)pops)->proc_read = (file_ops_read_fn)read;
                              ^
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c: In function ‘kfio_set_file_ops_write_handler’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:310:30: error: dereferencing pointer to incomplete type
     ((struct proc_ops *)pops)->proc_write = (file_ops_write_fn)write;
                              ^
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c: In function ‘kfio_set_file_ops_open_handler’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:315:30: error: dereferencing pointer to incomplete type
     ((struct proc_ops *)pops)->proc_open = (file_ops_open_fn)open;
                              ^
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c: In function ‘kfio_set_file_ops_release_handler’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.c:320:30: error: dereferencing pointer to incomplete type
     ((struct proc_ops *)pops)->proc_release = (file_ops_release_fn)release;
                              ^
make[5]: *** [/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kfile.o] Error 1
make[5]: *** Waiting for unfinished jobs....
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcpu.c: In function ‘kfio_map_cpus_to_read_queues’:
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcpu.c:214:5: warning: variable length array ‘node_hist’ is used [-Wvla]
     uint32_t node_hist[nodes_possible], node_map[nodes_possible];
     ^
/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build/kcpu.c:214:5: warning: variable length array ‘node_map’ is used [-Wvla]
make[4]: *** [/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build] Error 2
make[3]: *** [sub-make] Error 2
make[3]: Leaving directory `/usr/src/kernels/5.4.17-2136.305.5.4.el7uek.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/iomemory-vsl4/5.4.17-e2084ae/build'
```

**Comment by bplein** [comment] 2022-04-12 18:50
Don't check out 5.12. Try with main branch.

**Comment by mattboston** [comment] 2022-04-12 19:54
The original post was using the main branch.  Are there any tricks with Oracle Linux 7 with UEK?  Based on the Sandisk docs, I got all the appropriate rpms installed plus some extra ones that weren't documented.

**Comment by mattboston** [comment] 2022-04-13 14:12
Here's the latest logs from trying to "make dkms".  I'm not a developer, but if there's some tips/tricks/hints on how to debug this, I'll definitely try.

[dkms2.log](https://github.com/RemixVSL/iomemory-vsl4/files/8482120/dkms2.log)

**Comment by snuf** [comment] 2022-04-14 05:59
@mattboston fix should be in `main` now. I reintroduced the check that was missing, which should get you to something that compiles.

**Comment by mattboston** [comment] 2022-04-14 12:49
Just pulled down changes and now getting new errors
[dkms3.log](https://github.com/RemixVSL/iomemory-vsl4/files/8489260/dkms3.log)
.

**Comment by snuf** [comment] 2022-04-14 13:18
@mattboston there is something odd with your headers. `1649939516.510  KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS=1` in the log indicates your kernel uses proc_ops, however when compiling it barfs that they should be file_operations. I tested the code on 5.4.0 (Ubuntu) which uses proc_ops. Can you get the logs from the kfio_config dir for that test?

**Comment by mattboston** [comment] 2022-04-14 13:31
I'm hoping this is what you're looking for.  Let me know if there's anything else you need or want me to run
[kfio_config.log](https://github.com/RemixVSL/iomemory-vsl4/files/8489522/kfio_config.log)
.

**Comment by snuf** [comment] 2022-04-14 13:41
I've spun up a test Oracle 7 box. The issue is indeed that it's falsely marking the test as successful, while it should mark it failed:
```[vagrant@fio2 iomemory-vsl4-4.3.7]$ cat kfio_config/KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS/kfioc_test.log 
[-snip-]
/home/vagrant/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/kfio_config/KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS/kfioc_test.c: In function 'kfioc_has_proc_create_data':
/home/vagrant/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/kfio_config/KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS/kfioc_test.c:9:5: warning: passing argument 4 of 'proc_create_data' from incompatible pointer type [enabled by default]
     return proc_create_data(NULL, 0, NULL, pops, NULL);
     ^
In file included from /home/vagrant/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/kfio_config/KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS/kfioc_test.c:4:0:
./include/linux/proc_fs.h:45:31: note: expected 'const struct file_operations *' but argument is of type 'const struct proc_ops *'
 extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
                               ^
/home/vagrant/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/kfio_config/KFIOC_X_PROC_CREATE_DATA_WANTS_PROC_OPS/kfioc_test.c:9:5: warning: 'pops' is used uninitialized in this function [-Wuninitialized]
     return proc_create_data(NULL, 0, NULL, pops, NULL);
     ^
[-snip-]
```
It should -Werror there and bomb, but it doesn't.

**Comment by snuf** [comment] 2022-04-14 13:44
Yep, adding `-Werror` it makes the behavior as expected. I wonder why I didn't have -Werror there hmmm....
```--- a/root/usr/src/iomemory-vsl4-4.3.7/kfio_config.sh
+++ b/root/usr/src/iomemory-vsl4-4.3.7/kfio_config.sh
@@ -353,7 +353,7 @@ void *kfioc_has_proc_create_data(struct inode *inode)
     return proc_create_data(NULL, 0, NULL, pops, NULL);
 }
 '
-    kfioc_test "$test_code" "$test_flag" 1 -Werror-implicit-function-declaration
+    kfioc_test "$test_code" "$test_flag" 1 "-Werror-implicit-function-declaration -Werror"
 }
```

**Comment by snuf** [comment] 2022-04-14 14:03
@mattboston fix is in `main` now:
```[   71.809152] fioinf ioDrive driver 5.4.17-9379af0-4.3.7.1205     loading...
...
[   74.723843] fioinf ioMemory SX300-1300 0000:00:04.0: probed fct0
[   74.850297] fioinf ioMemory SX300-1300 0000:00:04.0: sector_size=4096
[   74.851137] fioinf ioMemory SX300-1300 0000:00:04.0: Setting channel range data to [2 .. 1023]
[   75.498794] fioinf ioMemory SX300-1300 0000:00:04.0: Found metadata in EBs 348-166, loading...
[   76.411302] fioinf ioMemory SX300-1300 0000:00:04.0: Device has no Virtual Partitions.  Creating compatibility Virtual Partition fioa.
[   76.412482] fioinf ioMemory SX300-1300 0000:00:04.0: Created device of size 1249999998976 bytes with 305175781 sectors of 4096 bytes (180976729 mapped).
[   76.415833] fioinf ioMemory SX300-1300 0000:00:04.0: Creating block device fioa: major: 250 minor: 0 sector size: 4096...
[   76.418950]  fioa: fioa1
[   76.419498] fioinf ioMemory SX300-1300 0000:00:04.0: Exposing Virtual Partition fioa of size 1249999998976 bytes with 305175781 sectors of 4096 bytes (180976729 mapped).
[   76.421310] fioinf ioMemory SX300-1300 0000:00:04.0: Attach succeeded.
```

**Comment by mattboston** [comment] 2022-04-14 14:51
Got some warnings, but I think it worked.  Unfortunately I can't confirm until I move the Fusion-IO's over from the old server, which requires a change ticket on our side.  Do you think it looks like it compiled correctly?
[dkms4.log](https://github.com/RemixVSL/iomemory-vsl4/files/8490048/dkms4.log)

**Comment by snuf** [comment] 2022-04-14 15:10
Looks good to me, the two warnings are "standard" and a gcc bounds check for vla's this should be replaced with a `malloc`. The only thing that sticks out is the `deprecated feature: REMAKE_INITRD` as I have no idea what that is about.

**Comment by mattboston** [comment] 2022-04-14 15:11
Excellent.  Thank you very much.  Feel free to mark as closed.

**Comment by mattboston** [comment] 2022-04-14 15:12
When I move the cards, I'll re-open or create a new if there are issues.

**Comment by snuf** [comment] 2022-04-14 22:36
Cool!

**Closed as completed by snuf** 2022-04-14 22:36 UTC
Labels: bug
